"""
build_readme.py - turns tools/README.template.md into README.md.

Every table of numbers (memory maps, register traces, sample runs, final
registers) is generated by running the programs on the Basic Computer model,
so the README cannot drift away from what the programs really do.
It also writes SCREENSHOTS.md, a checklist built from the image links.

Run from the repository root:  python3 tools/build_readme.py
"""
import os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
from basic_computer import assemble, run, fetch_micro_trace, signed

PROG = lambda n: os.path.join(ROOT, "programs", n)

RUNS = {
    "P03_ADD.a": [(25, 17), (-40, 15), (-1, 1), (30000, 10000)],
    "P04_SUBTRACT.a": [(50, 18), (18, 50), (-7, -7), (0, 1)],
    "P05_LOGIC.a": [(12, 10), (5, 3), (255, 15)],
    "P10_SUM_UNTIL_NEGATIVE.a": [(4, 10, 0, 6, -3), (-5,), (7, 8, -1)],
    "P11_SUM_UNTIL_ZERO.a": [(8, 12, -5, 0), (0,), (100, 200, 300, 0)],
}


def val(v):
    """16-bit value as unsigned decimal, with the signed reading in brackets."""
    return "%d (%d)" % (v, signed(v)) if v & 0x8000 else str(v)


def table(head, rows):
    out = ["| " + " | ".join(head) + " |", "| " + " | ".join([":---"] * len(head)) + " |"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def t_program(name):
    with open(PROG(name)) as f:
        return "```\n" + f.read().rstrip("\n") + "\n```"


def t_memmap(name):
    _, listing = assemble(PROG(name))
    rows = [(a, "%03X" % a, "%04X" % w, lab, txt) for a, lab, txt, w in listing]
    return table(["Addr (dec)", "Addr (hex)", "Code (hex)", "Label", "Instruction"], rows)


def t_trace(name, dr=False):
    _, tr = run(PROG(name))
    head = ["Step", "PC before", "Instruction", "IR (hex)", "AC"] + (["DR"] if dr else []) + ["E", "PC", "AR", "IR (dec)"]
    rows = []
    for t in tr:
        r = [t["step"], t["pc_before"], t["instr"], "%04X" % t["ir"], val(t["ac"])]
        if dr:
            r.append(val(t["dr"]))
        r += [t["e"], t["pc"], t["ar"], t["ir"]]
        rows.append(r)
    return table(head, rows)


def t_runs(name):
    rows = []
    for ins in RUNS[name]:
        m, _ = run(PROG(name), ins)
        rows.append((", ".join(str(i) for i in ins), ", ".join(str(o) for o in m.output)))
    outhead = "Output(s) displayed"
    if name == "P05_LOGIC.a":
        outhead += " (AND, OR, NOT A, NOT B, XOR, NOR, NAND)"
    return table(["Input(s) typed", outhead], rows)


def t_fetch():
    rows = []
    for step, micro, ar, pc, ir in fetch_micro_trace(PROG("P03_ADD.a")):
        arc = "%d (%X)" % (ar, ar) if ar else "0"
        irc = "%d (%04X)" % (ir, ir) if ir else "0"
        if step == 5:
            irc += " → INP"
        rows.append(("**%s**" % step, "`%s`" % micro if micro != "-" else "--", arc, pc, irc))
    return table(["Micro-step", "Microinstruction", "AR", "PC", "IR"], rows)


def t_final(name):
    m, _ = run(PROG(name))
    rows = [("AC", val(m.AC), "%04X" % m.AC), ("E", m.E, "%X" % m.E),
            ("PC", m.PC, "%03X" % m.PC), ("AR", m.AR, "%03X" % m.AR),
            ("IR", m.IR, "%04X" % m.IR)]
    return table(["Register", "Decimal", "Hex"], rows)


def t_logic():
    m, _ = run(PROG("P05_LOGIC.a"), (12, 10))
    names = ["A AND B", "A OR B", "NOT A", "NOT B", "A XOR B", "A NOR B", "A NAND B"]
    words = [12, 10] + [o & 0xFFFF for o in m.output]
    labels = ["A = 12", "B = 10"] + names
    rows = []
    for lab, w in zip(labels, words):
        b = "{:016b}".format(w)
        rows.append((lab, " ".join(b[i:i + 4] for i in range(0, 16, 4)), "%04X" % w, signed(w)))
    return table(["Operation", "16-bit result (binary)", "Hex", "Decimal output"], rows)


def expand(m):
    tok = m.group(1).split()
    cmd, args = tok[0], tok[1:]
    if cmd == "PROGRAM": return t_program(args[0])
    if cmd == "MEMMAP": return t_memmap(args[0])
    if cmd == "TRACE": return t_trace(args[0], dr=("dr" in args[1:]))
    if cmd == "RUNS": return t_runs(args[0])
    if cmd == "FETCH": return t_fetch()
    if cmd == "FINAL": return t_final(args[0])
    if cmd == "LOGICTABLE": return t_logic()
    raise ValueError("unknown token " + m.group(0))


def main():
    with open(os.path.join(HERE, "README.template.md")) as f:
        text = f.read()
    text = re.sub(r"\{\{(.+?)\}\}", expand, text)
    assert "{{" not in text
    with open(os.path.join(ROOT, "README.md"), "w") as f:
        f.write(text)

    # ---- screenshot checklist ----
    shots = re.findall(r"!\[(.*?)\]\((screenshots/[^)]+)\)", text)
    names = [s[1] for s in shots]
    assert len(names) == len(set(names)), "duplicate screenshot file names"
    lines = [
        "# Screenshot checklist", "",
        "The README links to %d screenshots in `screenshots/`. Take them from **your own** CPU Sim window, "
        "save each as PNG with exactly the file name shown, and tick it off here. "
        "Until a file exists, GitHub shows the caption text in its place." % len(shots), "",
        "**Tips**", "",
        "- Use one window size for all shots (maximised is fine) and crop out the desktop.",
        "- Registers pane *Data* = **Unsigned Dec** for the trace practicals (6 to 9); RAM pane *Data* = **Hex**.",
        "- For the step-by-step shots, keep the register pane and the highlighted instruction both visible.",
        "- Add your name or roll number somewhere in the first shot of each practical if your teacher asks for it.", "",
    ]
    cur = None
    for cap, path in shots:
        tag = os.path.basename(path)[:3]
        if tag != cur:
            cur = tag
            n = int(tag[1:])
            lines += ["", "## Practical %d" % n, "", "| Done | File | What it must show |", "| :--- | :--- | :--- |"]
        lines.append("| [ ] | `%s` | %s |" % (os.path.basename(path), cap))
    with open(os.path.join(ROOT, "SCREENSHOTS.md"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print("README.md written;", len(shots), "screenshot slots")


main()
